### ISSUE TITLE
Messages containing dates produce incorrect GO syntax

### ISSUE THREAD

**Issue by DevDevious** [200sc/bebop#2]
```
message MyObj {
    1 -> date Start;
    2 -> date End;
}
```

Results in code such as:

`iohelp.WriteInt64Bytes(buf[at:], (*bbp.Start.UnixNano()/100))`
`iohelp.WriteInt64Bytes(buf[at:], (*bbp.End.UnixNano()/100))`

`golangci-lint run my_obj.go`

```
level=error msg="[linters context] typechecking error: my_obj.go:87:27: invalid operation: cannot indirect bbp.Start.UnixNano() (value of type int64)"
level=error msg="[linters context] typechecking error: my_obj.go:95:27: invalid operation: cannot indirect bbp.End.UnixNano() (value of type int64)"
```

**Comment by 200sc** [comment]
On it, thank you for the report.

**Comment by DevDevious** [comment]
Also, is the "tick" concept and hence the division by 100 really necessary?

**Comment by 200sc** [comment]
Unfortunately the 'tick' logic is necessary to keep compatibility with the standard.  Otherwise generated messages could fail to be parsed by other bebop parsers. 

I'm not particularly fond of it myself.

**Comment by DevDevious** [comment]
@200sc makes sense. Thanks for the quick fix.
