### ISSUE TITLE
Upstream compatibility: nonstandard enum sizes

### ISSUE THREAD

**Issue by 200sc** [200sc/bebop#24]
c.f. https://github.com/RainwayApp/bebop/issues/156

**Comment by sveinnthorarins** [comment]
Any plans to implement this?

**Comment by 200sc** [comment]
@sveinnthorarins PR is up covering this, if you're actively attempting to use this feature and want to verify it before I cut a new version.

**Comment by 200sc** [comment]
@sveinnthorarins I added the new enums to the compatibility test suite after adjusting the generated writers, thanks! I've merged this in as a pre-release v0.4.0 for now.
