### ISSUE TITLE
Include binaries in releases?

### ISSUE THREAD

**Issue by 200sc** [200sc/bebop#26]
It would take a little bit of automation work to build them but would be theoretically trivial to build binaries for any platform supported by Go, if there's a desire to prebuild them. With Go dependencies one would usually already be coding in go and `go install` the tool directly, however.

**Comment by gedw99** [comment]
Oh that would be nice helper in general.

**Comment by 200sc** [comment]
Present in the v0.4.0 pre-release:

https://github.com/200sc/bebop/releases/tag/v0.4.0
